---

- hosts: ios
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Configure hostname
      ios_config:
        lines:
          - hostname SW1

    - name: Set SNMP
      ios_config:
        lines:
          - snmp-server community mycomm RO